// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function AddUdpClient(arg1:types.ServerClient):Promise<types.ConnectResult>;

export function ConnectUdpClient(arg1:number):Promise<types.ConnectResult>;

export function DeleteUdpClient(arg1:number):Promise<types.ConnectResult>;

export function DisconnectUdpClient(arg1:number):Promise<types.ConnectResult>;

export function GetAllUdpClients():Promise<types.ConnectResult>;

export function GetUdpClientData(arg1:number):Promise<types.ConnectResult>;

export function GetUdpClientStatus(arg1:number):Promise<types.ConnectResult>;

export function SendMessage(arg1:number,arg2:string,arg3:string):Promise<types.ConnectResult>;

export function SendScheduledMessage(arg1:number,arg2:string,arg3:string,arg4:number):Promise<types.ConnectResult>;

export function StopScheduledMessage(arg1:number):Promise<types.ConnectResult>;

export function UpdateUdpClient(arg1:types.ServerClient):Promise<types.ConnectResult>;
