// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function AddTCPClient(arg1:types.ServerClient):Promise<types.ConnectResult>;

export function ConnectTCPClient(arg1:number):Promise<types.ConnectResult>;

export function DeleteTCPClient(arg1:number):Promise<types.ConnectResult>;

export function DisconnectTCPClient(arg1:number):Promise<types.ConnectResult>;

export function GetAllTCPClients():Promise<types.ConnectResult>;

export function GetTCPClientData(arg1:number):Promise<types.ConnectResult>;

export function GetTCPClientStatus(arg1:number):Promise<types.ConnectResult>;

export function SendMessage(arg1:number,arg2:string,arg3:string):Promise<types.ConnectResult>;

export function SendScheduledMessage(arg1:number,arg2:string,arg3:string,arg4:number):Promise<types.ConnectResult>;

export function StopScheduledMessage(arg1:number):Promise<types.ConnectResult>;

export function UpdateTCPClient(arg1:types.ServerClient):Promise<types.ConnectResult>;
