// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTCPServer(arg1) {
  return window['go']['control']['FuncTcpServer']['AddTCPServer'](arg1);
}

export function CheckConnectionStatus() {
  return window['go']['control']['FuncTcpServer']['CheckConnectionStatus']();
}

export function DeleteTCPServer(arg1) {
  return window['go']['control']['FuncTcpServer']['DeleteTCPServer'](arg1);
}

export function DisconnectClient(arg1, arg2) {
  return window['go']['control']['FuncTcpServer']['DisconnectClient'](arg1, arg2);
}

export function GetAllTCPServers() {
  return window['go']['control']['FuncTcpServer']['GetAllTCPServers']();
}

export function GetTCPServerData(arg1) {
  return window['go']['control']['FuncTcpServer']['GetTCPServerData'](arg1);
}

export function GetTCPServerStatus(arg1) {
  return window['go']['control']['FuncTcpServer']['GetTCPServerStatus'](arg1);
}

export function SendMessage(arg1, arg2, arg3) {
  return window['go']['control']['FuncTcpServer']['SendMessage'](arg1, arg2, arg3);
}

export function StartTCPServer(arg1) {
  return window['go']['control']['FuncTcpServer']['StartTCPServer'](arg1);
}

export function StopTCPServer(arg1) {
  return window['go']['control']['FuncTcpServer']['StopTCPServer'](arg1);
}

export function UpdateTCPServer(arg1) {
  return window['go']['control']['FuncTcpServer']['UpdateTCPServer'](arg1);
}
