// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddUdpServer(arg1) {
  return window['go']['control']['FuncUdpServer']['AddUdpServer'](arg1);
}

export function DeleteUdpServer(arg1) {
  return window['go']['control']['FuncUdpServer']['DeleteUdpServer'](arg1);
}

export function DisconnectClient(arg1, arg2) {
  return window['go']['control']['FuncUdpServer']['DisconnectClient'](arg1, arg2);
}

export function GetAllUdpServers() {
  return window['go']['control']['FuncUdpServer']['GetAllUdpServers']();
}

export function GetUdpServerData(arg1) {
  return window['go']['control']['FuncUdpServer']['GetUdpServerData'](arg1);
}

export function GetUdpServerStatus(arg1) {
  return window['go']['control']['FuncUdpServer']['GetUdpServerStatus'](arg1);
}

export function SendMessage(arg1, arg2, arg3) {
  return window['go']['control']['FuncUdpServer']['SendMessage'](arg1, arg2, arg3);
}

export function StartUdpServer(arg1) {
  return window['go']['control']['FuncUdpServer']['StartUdpServer'](arg1);
}

export function StopUdpServer(arg1) {
  return window['go']['control']['FuncUdpServer']['StopUdpServer'](arg1);
}

export function UpdateUdpServer(arg1) {
  return window['go']['control']['FuncUdpServer']['UpdateUdpServer'](arg1);
}
