// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddUdpClient(arg1) {
  return window['go']['control']['FuncUdpClient']['AddUdpClient'](arg1);
}

export function ConnectUdpClient(arg1) {
  return window['go']['control']['FuncUdpClient']['ConnectUdpClient'](arg1);
}

export function DeleteUdpClient(arg1) {
  return window['go']['control']['FuncUdpClient']['DeleteUdpClient'](arg1);
}

export function DisconnectUdpClient(arg1) {
  return window['go']['control']['FuncUdpClient']['DisconnectUdpClient'](arg1);
}

export function GetAllUdpClients() {
  return window['go']['control']['FuncUdpClient']['GetAllUdpClients']();
}

export function GetUdpClientData(arg1) {
  return window['go']['control']['FuncUdpClient']['GetUdpClientData'](arg1);
}

export function GetUdpClientStatus(arg1) {
  return window['go']['control']['FuncUdpClient']['GetUdpClientStatus'](arg1);
}

export function SendMessage(arg1, arg2, arg3) {
  return window['go']['control']['FuncUdpClient']['SendMessage'](arg1, arg2, arg3);
}

export function SendScheduledMessage(arg1, arg2, arg3, arg4) {
  return window['go']['control']['FuncUdpClient']['SendScheduledMessage'](arg1, arg2, arg3, arg4);
}

export function StopScheduledMessage(arg1) {
  return window['go']['control']['FuncUdpClient']['StopScheduledMessage'](arg1);
}

export function UpdateUdpClient(arg1) {
  return window['go']['control']['FuncUdpClient']['UpdateUdpClient'](arg1);
}
