// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTCPClient(arg1) {
  return window['go']['control']['FuncTcpClient']['AddTCPClient'](arg1);
}

export function ConnectTCPClient(arg1) {
  return window['go']['control']['FuncTcpClient']['ConnectTCPClient'](arg1);
}

export function DeleteTCPClient(arg1) {
  return window['go']['control']['FuncTcpClient']['DeleteTCPClient'](arg1);
}

export function DisconnectTCPClient(arg1) {
  return window['go']['control']['FuncTcpClient']['DisconnectTCPClient'](arg1);
}

export function GetAllTCPClients() {
  return window['go']['control']['FuncTcpClient']['GetAllTCPClients']();
}

export function GetTCPClientData(arg1) {
  return window['go']['control']['FuncTcpClient']['GetTCPClientData'](arg1);
}

export function GetTCPClientStatus(arg1) {
  return window['go']['control']['FuncTcpClient']['GetTCPClientStatus'](arg1);
}

export function SendMessage(arg1, arg2, arg3) {
  return window['go']['control']['FuncTcpClient']['SendMessage'](arg1, arg2, arg3);
}

export function SendScheduledMessage(arg1, arg2, arg3, arg4) {
  return window['go']['control']['FuncTcpClient']['SendScheduledMessage'](arg1, arg2, arg3, arg4);
}

export function StopScheduledMessage(arg1) {
  return window['go']['control']['FuncTcpClient']['StopScheduledMessage'](arg1);
}

export function UpdateTCPClient(arg1) {
  return window['go']['control']['FuncTcpClient']['UpdateTCPClient'](arg1);
}
