// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function AddMessage(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<types.ConnectResult>;

export function DeleteMessage(arg1:number):Promise<types.ConnectResult>;

export function DeleteMessageByServerID(arg1:number,arg2:number):Promise<types.ConnectResult>;

export function GetAllMessages(arg1:number):Promise<types.ConnectResult>;

export function GetServerAllMessages(arg1:number,arg2:number):Promise<types.ConnectResult>;
