// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMessage(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['control']['Message']['AddMessage'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function DeleteMessage(arg1) {
  return window['go']['control']['Message']['DeleteMessage'](arg1);
}

export function DeleteMessageByServerID(arg1, arg2) {
  return window['go']['control']['Message']['DeleteMessageByServerID'](arg1, arg2);
}

export function GetAllMessages(arg1) {
  return window['go']['control']['Message']['GetAllMessages'](arg1);
}

export function GetServerAllMessages(arg1, arg2) {
  return window['go']['control']['Message']['GetServerAllMessages'](arg1, arg2);
}
