// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllTCPServerConn(arg1) {
  return window['go']['control']['TcpServerConn']['GetAllTCPServerConn'](arg1);
}

export function GetTCPServerConn(arg1, arg2) {
  return window['go']['control']['TcpServerConn']['GetTCPServerConn'](arg1, arg2);
}
