// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function GetAllUdpServerConn(arg1:number):Promise<types.ConnectResult>;

export function GetUDPServerConn(arg1:number,arg2:number):Promise<types.ConnectResult>;
