// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllUdpServerConn(arg1) {
  return window['go']['control']['UdpServerConn']['GetAllUdpServerConn'](arg1);
}

export function GetUDPServerConn(arg1, arg2) {
  return window['go']['control']['UdpServerConn']['GetUDPServerConn'](arg1, arg2);
}
