// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SetDB():Promise<void>;

export function ShowWarningDialog(arg1:string,arg2:string):Promise<void>;
