// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SetDB() {
  return window['go']['main']['App']['SetDB']();
}

export function ShowWarningDialog(arg1, arg2) {
  return window['go']['main']['App']['ShowWarningDialog'](arg1, arg2);
}
